export const NavbarData = {
  logo: '/images/black-logo.svg',
  navLinks: [
    {
      label: 'Home',
      url: '/'
    },
    {
      label: 'Features',
      url: '/feature'
    },
    {
      label: 'Pricing',
      url: '/pricing'
    }
  ]
}

export const FooterData = {
  logo: '/images/logo.png',
  socialLinks: [
    {
      icon: '/images/insta.png',
      url: 'https://www.instagram.com/kodezi.co'
    },
    {
      icon: '/images/linkedin.png',
      url: 'https://www.linkedin.com/'
    },
    {
      icon: '/images/twitter.png',
      url: 'https://www.twitter.com/kodeziHQ'
    },
    {
      icon: '/images/youtube.png',
      url: 'https://www.youtube.com/'
    }
  ],

  homeLinks: [
    {
      label: 'Privacy policy',
      url: '/privacy-policy'
    },
    {
      label: 'Terms of service',
      url: '/'
    }
  ],

  aboutUsLinks: [
    {
      label: 'info@kodezi.com',
      url: 'mailto:info@kodezi.com'
    },
    {
      label: 'support@kodezi.com',
      url: 'mailto:info@kodezi.com'
    },
    {
      label: 'careers@kodezi.com',
      url: 'mailto:info@kodezi.com'
    }
  ],

  newsLinks: [
    {
      label: 'Home',
      url: '/'
    },
    {
      label: 'Features',
      url: '/feature'
    },
    {
      label: 'Pricing',
      url: '/pricing'
    }
  ]
}

export const SignInData = {
  signUpImg: '/images/sign-up.svg',
  signInImg: '/images/sign-in.svg',
  signUpText: 'Already Signed up?',
  signInText: 'Are you new here?',
  signUpHeading: 'Sign Up On Kodezi',
  signInHeading: 'Sign in to kodezi',
  subTitle: 'Let’s get you setup so we can make coding easy for you!',
  subDetail:
    'Get access our AI coding debugging engine as well as access to written content AI engine to assist not only in programming but written content like essays! '
}

export const privacyPolicyData = {
  policyContent: `1. Introduction<br/><br/>
  Welcome to Ivella, Inc
  <br/><br/>
  Ivella, Inc (“us”, “we”, or “our”) operates https://www.ivella.co/ and Ivella mobile application (herein after referred to as “Service”).
  <br/><br/>
  Our Privacy Policy governs your visit to https://www.ivella.co/ and Ivella mobile application, and explains how we collect, safeguard and disclose information that results from your use of our Service.
  <br/><br/>
  We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
  <br/><br/>
  Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“agreement”).
  <br/><br/>
  2. Definitions
  SERVICE means the https://www.ivella.co/ website and Ivella mobile application operated by Ivella, Inc
  <br/><br/>
  PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
  <br/><br/>
  USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).
  <br/><br/>
  COOKIES are small files stored on your device (computer or mobile device).
  <br/><br/>
  DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.
  <br/><br/>
  DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
  <br/><br/>
  DATA SUBJECT is any living individual who is the subject of Personal Data.
  <br/><br/>
  THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
  <br/><br/>
  3. Information Collection and Use
  We collect several different types of information for various purposes to provide and improve our Service to you.
  <br/><br/>
  4. Types of Data Collected
  Personal Data
  <br/><br/>
  While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:
  <br/><br/>
  (a)  Email address
  <br/><br/>
  (b)  First name and last name 
  <br/><br/>
  (c)  Phone number
  <br/><br/>
  (d)  Address, State, Province, ZIP/Postal code, City
  <br/><br/>
  (e)  Cookies and Usage Data
  <br/><br/>
  We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or by emailing at info@ivella.co.
  <br/><br/>
  Usage Data
  <br/><br/>
  We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a mobile device (“Usage Data”).
  <br/><br/>
  This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
  <br/><br/>
  When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
  <br/><br/>
  Location Data
  <br/><br/>
  We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Service, to improve and customize our Service.
  <br/><br/>
  You can enable or disable location services when you use our Service at any time by way of your device settings.
  <br/><br/>
  Tracking Cookies Data
  <br/><br/>
  We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
  <br/><br/>
  Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.
  <br/><br/>
  You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
  <br/><br/>
  Examples of Cookies we use:
  <br/><br/>
  (a)  Session Cookies: We use Session Cookies to operate our Service.
  <br/><br/>
  (b)  Preference Cookies: We use Preference Cookies to remember your preferences and various settings.
  <br/><br/>
  (c)  Security Cookies: We use Security Cookies for security purposes.
  <br/><br/>
  (d)  Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.
  <br/><br/>
  Other Data
  <br/><br/>
  While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, non-disclosureagreements, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location and other data.
  <br/><br/>
  5. Use of Data
  Ivella, Inc uses the collected data for various purposes:
  <br/><br/>
  (a)  to provide and maintain our Service;
  <br/><br/>
  (b)  to notify you about changes to our Service;
  <br/><br/>
  (c)  to allow you to participate in interactive features of our Service when you choose to do so;
  <br/><br/>
  (d)  to provide customer support;
  <br/><br/>
  (e)  to gather analysis or valuable information so that we can improve our Service;
  <br/><br/>
  (f)   to monitor the usage of our Service;
  <br/><br/>
  (g)  to detect, prevent and address technical issues;
  <br/><br/>
  (h)  to fulfill any other purpose for which you provide it;
  <br/><br/>
  (i)   to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;
  <br/><br/>
  (j)   to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;
  <br/><br/>
  (k)  to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;
  <br/><br/>
  (l)   in any other way we may describe when you provide the information;
  <br/><br/>
  (m) for any other purpose with your consent.
  <br/><br/>
  6. Retention of Data
  We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
  <br/><br/>
  We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
  <br/><br/>
  7. Transfer of Data
  Your information, including Personal Data, may be transferred to – and maintained on– computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
  <br/><br/>
  If you are located outside United Stat es and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.
  <br/><br/>
  Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
  <br/><br/>
  Ivella, Inc will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
  <br/><br/>
  8. Disclosure of Data
  We may disclose personal information that we collect, or you provide:
  <br/><br/>
  (a)  Disclosure for Law Enforcement.
  <br/><br/>
  Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.
  <br/><br/>
  (b)  Business Transaction.
  <br/><br/>
  If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.
  <br/><br/>
  (c)  Other cases. We may disclose your information also:
  <br/><br/>
  (i)   to our subsidiaries and affiliates;
  <br/><br/>
  (ii)  to contractors, service providers, and other third parties we use to support our business;
  <br/><br/>
  (iii)  to fulfill the purpose for which you provide it;
  <br/><br/>
  (iv)  for any other purpose disclosed by us when you provide the information;
  <br/><br/>
  (v)  with your consent in any other cases;
  <br/><br/>
  (vi)  if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.
  <br/><br/>
  9. Security of Data
  The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
  <br/><br/>
  10. Your Data Protection Rights Under General Data Protection Regulation (GDPR)
  If you area resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR. – See more athttps://eur-lex.europa.eu/eli/reg/2016/679/oj
  <br/><br/>
  We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
  <br/><br/>
  If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at info@ivella.co.
  <br/><br/>
  In certain circumstances, you have the following data protection rights:
  <br/><br/>
  (a)  the right to access, update or to delete the information we have on you;
  <br/><br/>
  (b)  the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;
  <br/><br/>
  (c)  the right to object. You have the right to object to our processing of your Personal Data;
  <br/><br/>
  (d)  the right of restriction. You have the right to request that we restrict the processing of your personal information;
  <br/><br/>
  (e)  the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;
  <br/><br/>
  (f)   the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;
  <br/><br/>
  Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.
  <br/><br/>
  You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
  <br/><br/>
  11. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)
  CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law’s reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy. – See more at:https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/
  <br/><br/>
  According to CalOPPA we agree to the following:
  <br/><br/>
  (a)   users can visit our site anonymously;
  <br/><br/>
  (b)   our Privacy Policy link includes the word “Privacy”, and can easily be found on the page specified above on the homepage of our website;
  <br/><br/>
  (c)   users will be notified of any privacy policy changes on our Privacy Policy Page;
  <br/><br/>
  (d)   users are able to change their personal information by emailing us at info@ivella.co.
  <br/><br/>
  Our Policy on “Do Not Track” Signals:
  <br/><br/>
  We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.
  <br/><br/>
  You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
  <br/><br/>
  12. Service Providers
  We may employ third party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services or assist us in analyzing how our Service is used.
  <br/><br/>
  These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
  <br/><br/>
  13. Analytics
  We may use third-party Service Providers to monitor and analyze the use of our Service.
  <br/><br/>
  Google Analytics
  <br/><br/>
  GoogleAnalytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.
  <br/><br/>
  For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en
  <br/><br/>
  We also encourage you to review the Google's policy for safeguarding your data: https://support.google.com/analytics/answer/6004245.
  <br/><br/>
  Firebase
  <br/><br/>
  Firebase is analytics service provided by Google Inc.
  <br/><br/>
  You may opt-out of certain Firebase features through your mobile device settings, such as your device advertising settings or by following the instructions provided by Google in their Privacy Policy: https://policies.google.com/privacy?hl=en
  <br/><br/>
  For more information on what type of information Firebase collects, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en
  <br/><br/>
  14. CI/CD tools
  We may use third-party Service Providers to automate the development process of our Service.
  <br/><br/>
  <br/><br/>
  GitHub
  <br/><br/>
  GitHub is provided by GitHub, Inc.
  <br/><br/>
  GitHub is a development platform to host and review code, manage projects, and build software.
  <br/><br/>
  For more information on what data GitHub collects for what purpose and how the protection of the data is ensured, please visit GitHub Privacy Policy page: https://help.github.com/en/articles/github-privacy-statement.
  <br/><br/>
  <br/><br/>
  GitLab CI/CD 
  <br/><br/>
  <br/><br/>
  GitLabCI/CD is provided by GitLab, Inc.
  <br/><br/>
  <br/><br/>
  GitLab CI(Continuous Integration) service is a part of GitLab that build and test the software whenever developer pushes code to application.
  <br/><br/>
  GitLab CD(Continuous Deployment) is a software service that places the changes of every code in the production which results in every day deployment of production.
  <br/><br/>
  For more information on what data GitLab CI/CD collects for what purpose and how the protection of the data is ensured, please visit GitLab CI/CD Privacy Policy page: https://about.gitlab.com/privacy/.
  <br/><br/>
  <br/><br/>
  15. Behavioral Remarketing
  Ivella, Inc uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimize and serve ads based on your past visits to our Service.
  <br/><br/>
  Google Ads (AdWords)
  <br/><br/>
  Google Ads (AdWords) remarketing service is provided by Google Inc.
  <br/><br/>
  You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page: http://www.google.com/settings/ads
  <br/><br/>
  Google also recommends installing the Google Analytics Opt-out Browser Add-on – https://tools.google.com/dlpage/gaoptout – for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by GoogleAnalytics.
  <br/><br/>
  For more information on the privacy practices of Google, please visit the Google Privacy Terms web page:https://policies.google.com/privacy?hl=en
  <br/><br/>
  Twitter
  <br/><br/>
  Twitter remarketing service is provided by Twitter Inc.
  <br/><br/>
  You can opt-out from Twitter's interest-based ads by following their instructions: https://support.twitter.com/articles/20170405
  <br/><br/>
  You can learn more about the privacy practices and policies of Twitter by visiting their Privacy Policy page: https://twitter.com/privacy
  <br/><br/>
  Facebook
  <br/><br/>
  Facebook remarketing service is provided by Facebook Inc.
  <br/><br/>
  You can learn more about interest-based advertising from Facebook by visiting this page: https://www.facebook.com/help/164968693837950
  <br/><br/>
  To opt-out from Facebook's interest-based ads, follow these instructions from Facebook: https://www.facebook.com/help/568137493302217
  <br/><br/>
  Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the Digital Advertising Alliance.You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA http://www.aboutads.info/choices/, the Digital Advertising Alliance of Canada in Canada http://youradchoices.ca/or the European Interactive Digital Advertising Alliance in Europe http://www.youronlinechoices.eu/, or opt-out using your mobile device settings.
  <br/><br/>
  For more information on the privacy practices of Facebook, please visit Facebook's Data Policy: https://www.facebook.com/privacy/explanation
  <br/><br/>
  16. Payments
  We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).
  <br/><br/>
  We will not store or collect your payment card details.That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
  <br/><br/>
  The payment processors we work with are:
  <br/><br/>
  Apple Store In-App Payments:
  <br/><br/>
  Their Privacy Policy can be viewed at: https://www.apple.com/legal/privacy/en-ww/ /https://support.apple.com/en-us/HT203027
  <br/><br/>
  <br/><br/>
  Plaid:
  <br/><br/>
  Their End User Privacy Policy, Cookie Policy and Privacy Statement can be viewed at https://plaid.com/legal/.
  <br/><br/>
  17. Links to Other Sites
  Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
  <br/><br/>
  <br/><br/>
  We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
  <br/><br/>
  18. Children's Privacy
  Our Services are not intended for use by children under the age of 18 (“Child” or “Children”).
  <br/><br/>
  We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
  <br/><br/>
  19. Changes to This Privacy Policy
  We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
  <br/><br/>
  <br/><br/>
  We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.
  <br/><br/>
  You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
  <br/><br/>
  20. Contact Us
  If you have any questions about this Privacy Policy, please contact us:
  <br/><br/>
  By email: <a href="mailto:info@ivella.co">info@ivella.co</a>.
  <br/><br/>
  By visiting this page on our website: <a href="https://www.ivella.co/">https://www.ivella.co/</a>.`
}
export const LearingPageData = {
  Lheading: 'Peer to peer - student led learning',
  LsubHeading:
    'Learn any course taught by peers your own age. Explore hundreds of hours of video on various programming languages, cyber security, data science, and even web development. Challenge your skills learned via quizzes, earn credits through our reward program and redeem those credits to use torwards our premium ai features',
  cardsData: {
    cards: [
      {
        title: 'Web Development ',
        text: 'Explore the infrastructure of creating a website, domains, hosting, database integration and more.',
        image: {
          url: '/images/coding.svg',
          altText: 'image'
        }
      },
      {
        title: 'javascript',
        text: 'Learn the different frameworks of JavaScript such as React and Vue, learn how they are utilized in everyday sites and how to code using them.',

        image: {
          url: '/images/js.svg',
          altText: 'image'
        }
      },
      {
        title: 'Python',
        text: 'Take a dive into the easiest programming language to learn and master as a beginner. Learn how you can use python to program solutions to your own day to day life.',

        image: {
          url: '/images/python.svg',
          altText: 'image'
        }
      },
      {
        title: 'HTML & CSS',
        text: 'Immerge yourself into the connection and utilization of HTML & CSS in sites, learn various integration techniques to be a successful web developer.',

        image: {
          url: '/images/html-css.svg',
          altText: 'image'
        }
      },
      {
        title: 'UX Design',
        text: 'Design your first UX design, learn how to use Figma and Adobe XD in order to integrate and maintain that design concept throughout the point. ',

        image: {
          url: '/images/ux.svg',
          altText: 'image'
        }
      },
      {
        title: 'Intro to Coding',
        text: 'Design your first UX design, learn how to use Figma and Adobe XD in order to integrate and maintain that design concept throughout the point. ',

        image: {
          url: '/images/countdown.svg',
          altText: 'image'
        }
      },
      {
        title: 'cyber security',
        text: 'Find out what pen testing is and how to perform your first pen test. As well as learn how to protect yourself and others from cyber security exploits. ',

        image: {
          url: '/images/cyber.svg',
          altText: 'image'
        }
      },
      {
        title: 'App & games',
        text: 'Create your first game, learn the process behind making a game idea come to reality with the help of code and game design. ',

        image: {
          url: '/images/game.svg',
          altText: 'image'
        }
      }
    ]
  },
  popularvideocard: {
    mospopulerheading: 'Our Most Popular Videos',
    cards: [
      {
        title: 'Create Amazing Color Schemes for Your  UX Design',
        time: '08 hr 15 mins',
        image: {
          url: './images/UXDesign.jpg',
          altText: 'image'
        },
        icon: {
          url: './images/VidoeplayInco.svg',
          altText: 'image'
        },
        icontime: {
          url: './images/timerIcon.svg',
          altText: 'timerIcon.svg'
        }
      },
      {
        title: 'Create Amazing Color Schemes for Your UX Design',
        time: '08 hr 15 mins',
        image: {
          url: './images/UXDesign.jpg',
          altText: 'image'
        },
        icon: {
          url: './images/VidoeplayInco.svg',
          altText: 'image'
        },
        icontime: {
          url: './images/timerIcon.svg',
          altText: 'timerIcon.svg'
        }
      },
      {
        title: 'Create Amazing Color Schemes for Your UX Design',
        time: '08 hr 15 mins',
        image: {
          url: './images/UXDesign.jpg',
          altText: 'image'
        },
        icon: {
          url: './images/VidoeplayInco.svg',
          altText: 'image'
        },
        icontime: {
          url: './images/timerIcon.svg',
          altText: 'timerIcon.svg'
        }
      },
      {
        title: 'Create Amazing Color Schemes for Your UX Design',
        time: '08 hr 15 mins',
        image: {
          url: './images/UXDesign.jpg',
          altText: 'image'
        },
        icon: {
          url: './images/VidoeplayInco.svg',
          altText: 'image'
        },
        icontime: {
          url: './images/timerIcon.svg',
          altText: 'timerIcon.svg'
        }
      },
      {
        title: 'Create Amazing Color Schemes for Your UX Design',
        time: '08 hr 15 mins',
        image: {
          url: './images/UXDesign.jpg',
          altText: 'image'
        },
        icon: {
          url: './images/VidoeplayInco.svg',
          altText: 'image'
        },
        icontime: {
          url: './images/timerIcon.svg',
          altText: 'timerIcon.svg'
        }
      },
      {
        title: 'Create Amazing Color Schemes for Your UX Design',
        time: '08 hr 15 mins',
        image: {
          url: './images/UXDesign.jpg',
          altText: 'image'
        },
        icon: {
          url: './images/VidoeplayInco.svg',
          altText: 'image'
        },
        icontime: {
          url: './images/timerIcon.svg',
          altText: 'timerIcon.svg'
        }
      },
      {
        title: 'Create Amazing Color Schemes for Your UX Design',
        time: '08 hr 15 mins',
        image: {
          url: './images/UXDesign.jpg',
          altText: 'image'
        },
        icon: {
          url: './images/VidoeplayInco.svg',
          altText: 'image'
        },
        icontime: {
          url: './images/timerIcon.svg',
          altText: 'timerIcon.svg'
        }
      },
      {
        title: 'Create Amazing Color Schemes for Your UX Design',
        time: '08 hr 15 mins',
        image: {
          url: './images/UXDesign.jpg',
          altText: 'image'
        },
        icon: {
          url: './images/VidoeplayInco.svg',
          altText: 'image'
        },
        icontime: {
          url: './images/timerIcon.svg',
          altText: 'timerIcon.svg'
        }
      },
      {
        title: 'Create Amazing Color Schemes for Your UX Design',
        time: '08 hr 15 mins',
        image: {
          url: './images/UXDesign.jpg',
          altText: 'image'
        },
        icon: {
          url: './images/VidoeplayInco.svg',
          altText: 'image'
        },
        icontime: {
          url: './images/timerIcon.svg',
          altText: 'timerIcon.svg'
        }
      }
    ]
  },
  moreVideoCard: {
    WMtitle: 'Watch more Videos',
    Searchimg: {
      url: './images/Search.svg',
      alt: 'img'
    },
    cards: [
      {
        title: 'Web devlopment',
        image: {
          url: '/images/coding.svg',
          alt: 'img'
        },
        icon: {
          url: '/images/videoicon.svg',
          alt: 'img'
        }
      },
      {
        title: 'Javascript',
        image: {
          url: '/images/js.svg',
          alt: 'img'
        },
        icon: {
          url: '/images/videoicon.svg',
          alt: 'img'
        }
      },
      {
        title: 'Python',
        image: {
          url: '/images/python.svg',
          alt: 'img'
        },
        icon: {
          url: '/images/videoicon.svg',
          alt: 'img'
        }
      },
      {
        title: 'HTML & CSS',
        image: {
          url: '/images/html-css.svg',
          alt: 'img'
        },
        icon: {
          url: '/images/videoicon.svg',
          alt: 'img'
        }
      },
      {
        title: 'UX Design',
        image: {
          url: '/images/ux.svg',
          alt: 'img'
        },
        icon: {
          url: '/images/videoicon.svg',
          alt: 'img'
        }
      },
      {
        title: 'Intro To Coding',
        image: {
          url: '/images/countdown.svg',
          alt: 'img'
        },
        icon: {
          url: '/images/videoicon.svg',
          alt: 'img'
        }
      },
      {
        title: 'Cyber Security',
        image: {
          url: '/images/cyber.svg',
          alt: 'img'
        },
        icon: {
          url: '/images/videoicon.svg',
          alt: 'img'
        }
      },
      {
        title: 'App & Games',
        image: {
          url: '/images/game.svg',
          alt: 'img'
        },
        icon: {
          url: '/images/videoicon.svg',
          alt: 'img'
        }
      }
    ]
  },
  tiles: [
    {
      icon: {
        url: '/images/brain.svg',
        alt: 'img'
      },
      title: 'everyone gets to learn!',
      subTitle:
        'Kodezi’s learning platform is 100% student led, students upload videos they are skilled in while others view to learn them.',
      text: 'We bridge the gap between student lead learning vs watching hour long videos on YouTube and obtaining textbook knowledge which never helps you truly learn.',
      image: {
        url: '/images/open-code.png',
        altText: 'image'
      }
    }
  ],
  singlesectinotwo: [
    {
      icon: {
        url: '/images/phone.png',
        alt: 'img'
      },
      title: 'Get Rewarded For Learning!',
      subTitle:
        'Each video you watch or quiz you take, we reward you for gaining an extra bit of knowledge by credits.',
      text: 'Each video you watch and quiz you take comes with an incentive of earning credits. you can use these credits torwards our premium aI features!',
      image: {
        url: '/images/kodezilfrist.svg',
        altText: 'image'
      }
    }
  ],
  singlesectino: [
    {
      title: 'start using aI powered programming & writing tools!',
      // text: 'Get access to over 200,000 open-source code to use in your tasks and projects. Browse from our library or upload your own code to gain credits to use torwards our other features!',
      btnLabel: {
        label: 'Debug Now',
        url: '/'
      },
      image: {
        url: '/images/kodezilastimg.svg',
        altText: 'image'
      }
    }
  ]
}
// export const footercontent = {

// }
